//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Data
{
    using System.Data.Entity;
    using Migrations;

    public partial class PetStoreEntities : DbContext
    {
        public PetStoreEntities()
            : base("PetStore")
        {
            Database.SetInitializer(new MigrateDatabaseToLatestVersion<PetStoreEntities, Configuration>());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }

        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSpecies> ProductSpecies { get; set; }
        public virtual DbSet<Species> Species { get; set; }
    }
}
